<div class="static-page-body">

  <div class="static-page-image">
    <img src="/assets/img/content/shapes-background.jpg" alt="Background Image of Various Shapes" />
  </div>

  <div class="static-page-overlay">

    <section class="static-page-text">
      <h1> Welcome to Shape Share! </h1>

      <p>
        Shape-Share is a simple online image sharing platform where members can upload, react, save, and search for
        images of shapes. A Shape-Share image can be described by its color/s/ and respective shape/s/ using tags for
        intuitive searches and increased visibility within the community. Members can subscribe to other members to
        generate a personal feed based off their interests, as well as define a taste profile to help Shape-Share
        deliver recommendations. Connect with the community on discussion boards and comment on images to share the
        love. Organize uploads by album, save others' images as favorites, and/or return to previously viewed images
        with the history feature. All of these tools are available in the Member Dashboard, providing a unique
        experience for each member.
      </p>

      <p>
        With a focus on security, Shape-Share utilizes SSL, data-at-rest encryption, and many other techniques to
        protect members' personal data. Privacy settings can be adjusted to tailor the degree of "sharing" each member
        has with the rest of the Shape-Share community. All images are required to be created by the member that uploads
        them (using Paint, GIMP, etc.) and must be 100% original. Members agree to this when registering for an account.
        Shape-Share also monitors content for plagiarism, profanity, and general misconduct to keep the community safe
        and inclusive for all ages.
      </p>
    </section>

    <section class="static-page-text">
      <h2> Want to start sharing? </h2>

      <p>
        <a href="#" title="Register">"Register</a>
        for a free Shape-Share membership or
        <a href="#" title="Login">Login</a>
        to continue where you left off in the top right-hand corner of this page.
      </p>

    </section>
  </div>

</div>