version: '3.9'

services:  
  server:
    container_name: server
    build: 
      context: ./.docker/server/
      dockerfile: Dockerfile
    ports:
      - "${APACHE_PORTS}"
      - "${APACHE_SECURE_PORTS}"
    volumes:
      - ./src:/var/www
      - type: bind
        source: "${APACHE_CONFIG}"
        target: "${CONTAINER_APACHE_CONFIG}"
      - type: bind
        source: "${PHP_CONFIG}"
        target: "${CONTAINER_PHP_CONFIG}"
    networks:
      - php_net

  db:
    container_name: mysql
    build:
      context: ./.docker/db/
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD="${DOCKER_SECRETS_DIR} mysql_root_password"
      - MYSQL_PASSWORD="${DOCKER_SECRETS_DIR}mysql_password"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
    volumes:
      - type: bind
        source: "${MYSQL_DATA_DIR}"
        target: "${CONTAINER_DB_DATA_DIR}"
      - "${MYSQL_CONFIG}:${CONTAINER_MYSQL_CONFIG}:ro"
      - type: bind
        source: "${SSL_DIR}/certs/mysql"
        target: "${CONTAINER_SSL_DIR}/certs/mysql"
    ports: 
      - "${MYSQL_PORTS}"
    networks:
      - mysql_net
    restart: on-failure
    secrets:
      - mysql_root_password
      - mysql_password
    command: [ "mysqld",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--bind-address=0.0.0.0",
      "--log-error-verbosity",
      "--require_secure_transport=ON",
      "--ssl-ca=${SHAPE_SHARE_CA}",
      "--ssl-cert=${MYSQL_SERVER_CERT}",
      "--ssl-key=${MYSQL_SERVER_KEY}",
      "--default_authentication_plugin=mysql_native_password" ]

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    depends_on:
      - db
    ports:
      - "${ADMINER_PORTS}"
    networks:
      - mysql_net
    restart: always

networks:
  mysql_net:
    name: mysql_net
  php_net:
    name: php_net

secrets:
  mysql_password:
    file: "${PASSWORD_FILE}db_password.txt"
  mysql_root_password:
    file: "${PASSWORD_FILE}db_root_password.txt"







