version: "3.9"

services:  
  apache:
    container_name: apache
    build: 
      context: "${APACHE}"
      dockerfile: Dockerfile
    hostname: "${DOMAIN_NAME}"
    ports:
      - "${APACHE_PORTS}"
      - "${APACHE_SECURE_PORTS}"
    expose:
      - "${APACHE_SECURE_PORTS}"
    volumes:
      - "${APP_SRC}:${DOCKER_APP_ROOT}shape-share/"
      - "./.docker/apache/httpd.conf:/etc/apache2/httpd.conf"
      - "${APACHE_CONFIG}:${DOCKER_APACHE_CONFIG}"
      - "${APACHE_LOGS}:${DOCKER_APACHE_LOGS}"
    environment:
      APP_ROOT: "${APP_SRC}"
      SERVER_NAME: "${DOMAIN_NAME}"
      REDIRECT_HTTP_TO_HTTPS: "true"
      ENABLE_HSTS: "true"
      ENABLE_MOD_PROXY: "true"
    restart: always
    depends_on:
      - php-fpm
      - db
    networks:
      - backend
      - frontend

  php-fpm:
    container_name: php
    build:
      context: "${PHP}"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "${APP_SRC}:/var/www/html/shape-share/"
      - "${PHP_CONFIG}:${DOCKER_PHP_CONFIG}"
      - "${PHP_LOGS}:${DOCKER_PHP_LOGS}"
    environment:
      APP_ROOT: "${APP_SRC}"
    networks:
      - frontend
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
        - "${PHPMYADMIN_PORTS}"
    domainname: local.shape-share.com
    volumes:
      - "$PHPMYADMIN/config.inc.php:/etc/phpmyadmin/config.user.inc.php"
    environment:
      PMA_ABSOLUTE_URI: "local.shape-share.com:8081/phpmyadmin"
      PMA_HOSTS: "${DOMAIN_NAME}:8081"
      PMA_USER: "${MYSQL_USER}"
      PMA_PMADB: "${MYSQL_DATABASE}"
      PMA_PASSWORD_FILE: "${DOCKER_SECRETS}db_password"
      HIDE_PHP_VERSION: On
    depends_on:
      - db
    networks:
      - backend
    restart: unless-stopped
    secrets: 
      - db_password

  db:
    container_name: mariadb
    build: 
      context: "${MYSQL}"
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD_FILE: "${DOCKER_SECRETS}db_password"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_USER_FILE: "${DOCKER_SECRETS}db_root_user" 
      MYSQL_ROOT_PASSWORD_FILE: "${DOCKER_SECRETS}db_root_password"
      MYSQL_ROOT_HOST: "${DOMAIN_NAME}"
      SERVER_KEY: "${MYSQL_SERVER_KEY}"
      SERVER_CERT: "${MYSQL_SERVER_CERT}"
      CA_CERT: "${MYSQL_CA_CERT}"
    volumes:
      - "${MYSQL_DATA_DIR}:${DOCKER_MYSQL_DATA}"
      - "${MYSQL_CONFIG}:${DOCKER_MYSQL_CONFIG}"
      - "${MYSQL_SSL}:${DOCKER_MYSQL_SSL}"
    ports: 
      - "${MYSQL_PORTS}"
    restart: always
    depends_on:
      - php-fpm
    networks: 
      - backend
    secrets:
      - db_password
      - db_root_user
      - db_root_password

networks:
  frontend:
    driver: bridge
  backend: 
    driver: bridge

secrets:
  db_password:
    file: "${SECRETS}db_password.txt"
  db_user:
    file: "${SECRETS}db_root_password.txt"
  db_host:
    file: "${SECRETS}db_host.txt"
  db_root_user:
    file: "${SECRETS}db_root_user.txt"
  db_root_password:
    file: "${SECRETS}db_root_password.txt"