version: "3.9"

services:  
  apache:
    container_name: apache
    build: 
      context: "${APACHE}"
      dockerfile: Dockerfile
    hostname: "www.${DOMAIN_NAME}"
    ports:
      - "${APACHE_PORTS}"
      - "${APACHE_SECURE_PORTS}"
    expose:
      - 443
    volumes:
      - "${APP_ROOT}:${DOCKER_APP_ROOT}${DOMAIN_NAME}"
      - "${APACHE_CONFIG}:${DOCKER_APACHE_CONFIG}:ro"
      - "${APACHE_SSL}:${DOCKER_APACHE_SSL}:ro" 
      - "${APACHE_LOGS}:${DOCKER_APACHE_LOG}"
    environment:
      SERVER_NAME: "${DOMAIN_NAME}"
      REDIRECT_HTTP_TO_HTTPS: "true"
      ENABLE_HSTS: "true"
      ENABLE_MOD_PROXY: "true"
    restart: always
    networks:
      - frontend

  php:
    container_name: php
    build:
      context: "${PHP}"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "${APP_ROOT}:/var/www/html/${DOMAIN_NAME}"
      - "${PHP_CONFIG}:${DOCKER_PHP_CONFIG}"
      - "${PHP_LOGS}:${DOCKER_PHP_LOGS}"
    environment:
      PMA_HOST: "${DOMAIN_NAME}"
      PMA_PORT: "${PHP_PORTS}"
      PMA_USER: "${DOCKER_SECRETS}db_user"
      PMA_PASSWORD: "${DOCKER_SECRETS}db_password"
      MYSQL_PASSWORD: "${DOCKER_SECRETS}db_password"
      MYSQL_ROOT_PASSWORD: "${DOCKER_SECRETS}db_root_password"
    ports:
      - "${PHP_PORTS}"
    depends_on:
      - apache
    networks:
      - frontend
      - backend
    secrets: 
      - db_root_password

  db:
    container_name: mariadb
    build: 
      context: "${MYSQL}"
      dockerfile: Dockerfile
    environment:
      MYSQL_USER_FILE: "${DOCKER_SECRETS}db_user"
      MYSQL_PASSWORD_FILE: "${DOCKER_SECRETS}db_password"
      MYSQL_DATABASE_FILE: "${DOCKER_SECRETS}db_database"
      MYSQL_ROOT_USER_FILE: "${DOCKER_SECRETS}db_root_user" 
      MYSQL_ROOT_PASSWORD_FILE: "${DOCKER_SECRETS}db_root_password"
      MYSQL_ROOT_HOST: "${DOMAIN_NAME}"
      SERVER_KEY: "${MYSQL_SERVER_KEY}"
      SERVER_CERT: "${MYSQL_SERVER_CERT}"
      CA_CERT: "${MYSQL_CA_CERT}"
    volumes:
      - "${MYSQL_DATA_DIR}:${DOCKER_MYSQL_DATA}"
      - "${MYSQL_CONFIG}:${DOCKER_MYSQL_CONFIG}"
      - "${MYSQL_SSL}:${DOCKER_MYSQL_SSL}"
    ports: 
      - "${MYSQL_PORTS}"
    restart: always
    depends_on:
      - php
    networks: 
      - backend
    secrets:
      - db_user
      - db_password
      - db_database
      - db_root_user
      - db_root_password

networks:
  frontend:
    driver: bridge
  backend: 
    driver: bridge

secrets:
  db_password:
    file: "${SECRETS}db_password.txt"
  db_user:
    file: "${SECRETS}db_root_password.txt"
  db_host:
    file: "${SECRETS}db_host.txt"
  db_database:
    file: "${SECRETS}db_database.txt"
  db_root_user:
    file: "${SECRETS}db_root_user.txt"
  db_root_password:
    file: "${SECRETS}db_root_password.txt"