<!-- Closing <div class="content-container"> -->
</div>

<footer class="footer-container">
  <section class="footer-main-section">
    <div class="footer-main-item">
      <h3 class="footer-main-title"> About the Project </h3>
      <ul>
        <li><a href="#" title="Github README.md">
            <i class="fa-brands fa-github"></i> README</a></li>
        <li><a href="#" title="Development Package">
            <i class="fa-brands fa-github"></i> Repository</a></li>
        <li><a href="#" title="Developer's Portfolio">
            <i class="fa-brands fa-github"></i>
            <i class="fa-solid fa-graduation-cap"></i> Portfolio</a></li>
      </ul>
    </div>

    <div class="footer-main-item">
      <h3 class="footer-main-title"> Contact Us </h3>
      <ul>
        <li><a href="#" title="Help with Account">
            <i class="fa-solid fa-circle-info"></i> Help</a></li>
        <li><a href="#" title="Become an Admin">
            <i class="fa-solid fa-handshake-angle"></i> Careers</a></li>
        <li><a href="#" title="Advertise on Shape-Share">
            <i class="fa-solid fa-rectangle-ad"></i> Advertise</a></li>
      </ul>
    </div>

    <div class="footer-main-item">
      <h3 class="footer-main-title"> Stay Updated </h3>
      <p> Subscribe to our newsketter to get our latest news and updates. </p>
      <form class="footer-form">
        <input class="footer-form-email" type="email" name="email" placeholder="Enter email address..." />
        <input class="footer-form-submit" type="submit" value="Subscribe" />
      </form>
    </div>
  </section>

  <section class="footer-legal-section">
    <ul class="footer-legal-list">
      <li><a href="#" title="Terms of Use Legal Document">Terms of Use</a></li>
      <li><a href="#" title="Privacy Policy">Privacy Policy</a></li>
      <li> Nyki Anderson 2022 under MIT License </li>
    </ul>
  </section>
</footer>

</body>

</html>