<!doctype html>

<html lang="en">

  <head>
    <base href="local.shape-share.com" />
    <meta charset="utf-8" />
    <title> <?= $title; ?> </title>
    <meta name="description" content="<?= $description; ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="nykianderson" />

    <!-- Favicon File -->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

    <!-- Default Stylesheet File -->
    <link rel="stylesheet" href="assets/css/light_theme.css?v24" type="text/css" title="Light Theme" />

    <!-- Alternate Stylesheet File -->
    <link rel="alternate stylesheet" href="assets/css/dark_theme.css?v24" title="Dark Theme" />

    <!-- Font Awesome Icons Library -->
    <script src="https://kit.fontawesome.com/7d7fc3eb87.js?v=24" crossorigin="anonymous"></script>

    <!-- J_Query Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js?v=24"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorgin="anonymous" type="text/javascript">
    </script>

    <!-- AJAX Library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js?v=24" type="text/javascript"
      charset="utf-8"></script>

    <!-- Google ReCaptcha API -->
    <script src="https://www.google.com/recaptcha/api.js?v=24"></script>
  </head>

  <body>
    <nav class="navbar-container">
      <div class="logo">
        <a href="#" title="Home">
          <i class="fas fa-shapes"></i>
          <span class="logo-capital-letters">S</span>hape
          <span class="logo-capital-letters">S</span>hare
        </a>
      </div>
      <div class="navbar-dropdown">
        <div class="navbar-dropbtn">
          <i class="fa-solid fa-bars" title='Register/Login'></i>
        </div>
        <div class="navbar-dropdown-content">
          <a href="#" title="Register">Register
            <i class="fas fa-user-circle"></i>
          </a>
          <a href="#" title="Login">Login
            <i class="fas fa-sign-in-alt"></i>
        </div>
      </div>
    </nav>

    <div class="content-container">